### ISSUE TITLE
"Key is already in use"

### ISSUE THREAD

**Issue by nycmadu** [Oxillius/scope-profiles#1]
Generating public/private rsa key pair.
Enter file in which to save the key (/c/Users/nycma/.ssh/id_rsa): copy < !/.ssh/id_ed25519.pub
Enter passphrase (empty for no passphrase):
Enter same passphrase again:
Passphrases do not match.  Try again.
Enter passphrase (empty for no passphrase):
Enter same passphrase again:
Saving key "copy \026\026\026\026\026\026\026copy < !/.ssh/id_ed25519.pub" failed: No such file or directory

nycma@DESKTOP-IA259AJ MINGW64 ~

Hi so when I try to do step (2) I can't seem to find th .ssh key to make the request.

**Comment by Oxillius** [comment]
Hello,

I see your having issues with the Number 3 portion of Step (2). Once you run the ``ssh-keygen -o -t rsa -C "your@email.com"`` command that is part of Step (2) - 2, you should be able to navigate to the following folder.

![image](https://github.com/Oxillius/scope-profiles/assets/75226619/e6b0e530-49c5-4037-b022-b326c7ce0324)

If you're unable to find this folder, verify you have View Hidden Items enabled in your File Explorer. You can enable this by navigating to the menu bar below the directory path in File Explorer and selecting View -> Show -> Hidden Items.

![image](https://github.com/Oxillius/scope-profiles/assets/75226619/ae914e47-8538-48eb-ad84-e772f204d520)
